"""add canonical job analysis skills

Revision ID: 0424eb155cd9
Revises: 1659610156c5
Create Date: 2026-09-13 02:23:52.351524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0424eb155cd9'
down_revision: Union[str, Sequence[str], None] = '1659610156c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('canonical_required_skills', sa.Text(), nullable=True))
    op.add_column('job_analyses', sa.Column('canonical_preferred_skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'canonical_preferred_skills')
    op.drop_column('job_analyses', 'canonical_required_skills')
    # ### end Alembic commands ###
