"""add skill catalog reference to skills

Revision ID: 1659610156c5
Revises: 896308607279
Create Date: 2026-09-13 02:08:18.300080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1659610156c5'
down_revision: Union[str, Sequence[str], None] = '896308607279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('skill_catalog_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_skills_skill_catalog_id'), 'skills', ['skill_catalog_id'], unique=False)
    op.create_foreign_key(None, 'skills', 'skill_catalog', ['skill_catalog_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_index(op.f('ix_skills_skill_catalog_id'), table_name='skills')
    op.drop_column('skills', 'skill_catalog_id')
    # ### end Alembic commands ###
