"""link parsed resume data to resume

Revision ID: 7a9ca0881fae
Revises: fe47d67786bb
Create Date: 2026-09-12 18:06:17.646688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9ca0881fae'
down_revision: Union[str, Sequence[str], None] = 'fe47d67786bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_achievements_resume_id'), 'achievements', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'achievements', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('certifications', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_certifications_resume_id'), 'certifications', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'certifications', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('courses', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_resume_id'), 'courses', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('education', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_education_resume_id'), 'education', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'education', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('experiences', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiences_resume_id'), 'experiences', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'experiences', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_resume_id'), 'projects', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('skills', sa.Column('resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_skills_resume_id'), 'skills', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'skills', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_index(op.f('ix_skills_resume_id'), table_name='skills')
    op.drop_column('skills', 'resume_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_resume_id'), table_name='projects')
    op.drop_column('projects', 'resume_id')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_index(op.f('ix_experiences_resume_id'), table_name='experiences')
    op.drop_column('experiences', 'resume_id')
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.drop_index(op.f('ix_education_resume_id'), table_name='education')
    op.drop_column('education', 'resume_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_resume_id'), table_name='courses')
    op.drop_column('courses', 'resume_id')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_index(op.f('ix_certifications_resume_id'), table_name='certifications')
    op.drop_column('certifications', 'resume_id')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_index(op.f('ix_achievements_resume_id'), table_name='achievements')
    op.drop_column('achievements', 'resume_id')
    # ### end Alembic commands ###
