"""add interview reports

Revision ID: 7ca09b6586f7
Revises: 706422c5fc2f
Create Date: 2026-09-20 00:50:37.825966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca09b6586f7'
down_revision: Union[str, Sequence[str], None] = '706422c5fc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('technical_knowledge', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('communication', sa.Float(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('topics_to_improve', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_reports_interview_id'), 'interview_reports', ['interview_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_reports_interview_id'), table_name='interview_reports')
    op.drop_table('interview_reports')
    # ### end Alembic commands ###
