"""add file hash to resumes

Revision ID: 8034cb0559ac
Revises: c8914fa0bcb9
Create Date: 2026-09-12 19:15:01.241086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8034cb0559ac'
down_revision: Union[str, Sequence[str], None] = 'c8914fa0bcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'resumes',
    sa.Column('file_hash', sa.String(length=64), nullable=True)
    )
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_column('resumes', 'file_hash')
    # ### end Alembic commands ###
