"""add skill catalog and aliases

Revision ID: 896308607279
Revises: 9c6eedff9c1b
Create Date: 2026-09-13 01:26:02.700637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896308607279'
down_revision: Union[str, Sequence[str], None] = '9c6eedff9c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_catalog_canonical_name'), 'skill_catalog', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skill_catalog_normalized_name'), 'skill_catalog', ['normalized_name'], unique=True)
    op.create_table('skill_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', name='uq_skill_aliases_normalized_alias')
    )
    op.create_index(op.f('ix_skill_aliases_normalized_alias'), 'skill_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_normalized_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_skill_catalog_normalized_name'), table_name='skill_catalog')
    op.drop_index(op.f('ix_skill_catalog_canonical_name'), table_name='skill_catalog')
    op.drop_table('skill_catalog')
    # ### end Alembic commands ###
