"""add interview duration

Revision ID: b223f41c14ee
Revises: 7ca09b6586f7
Create Date: 2026-09-22 22:45:17.788314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b223f41c14ee'
down_revision: Union[str, Sequence[str], None] = '7ca09b6586f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "interview_sessions",
        sa.Column(
            "duration_minutes",
            sa.Integer(),
            server_default="30",
            nullable=False,
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'duration_minutes')
    # ### end Alembic commands ###
