"""require resume id for parsed data

Revision ID: c8914fa0bcb9
Revises: 7a9ca0881fae
Create Date: 2026-09-12 18:16:58.711433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8914fa0bcb9'
down_revision: Union[str, Sequence[str], None] = '7a9ca0881fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('certifications', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('education', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('experiences', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skills', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('experiences', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('education', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('certifications', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('achievements', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
